# Generated by Django 5.0.1 on 2024-02-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Parrot', 'Parrot'), ('Bunny', 'Bunny'), ('Other', 'Other')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
