# Generated by Django 5.0.1 on 2024-02-25 18:31

import petstagram.main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(max_length=250, upload_to='', validators=[petstagram.main_app.validators.validate_file_max_size_in_mb]),
        ),
    ]
