# Generated by Django 5.0.1 on 2024-02-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pet_user_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('user_profile', 'name')},
        ),
    ]
