# Generated by Django 5.0.3 on 2024-03-11 11:34

import MyMusicApp.base.validators.minlenvaluevalidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[MyMusicApp.base.validators.minlenvaluevalidator.minlenvaluevalidator]),
        ),
    ]
