# Generated by Django 4.0.2 on 2024-02-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('egn', models.CharField(default='Fill this in', max_length=10, verbose_name='EGN')),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.IntegerField(choices=[(1, 'Software Engineering'), (2, 'HR'), (3, 'Security')])),
                ('company', models.CharField(choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Lockheed Martin', 'Lockheed Martin')], max_length=15)),
            ],
        ),
    ]
