# Generated by Django 4.0.2 on 2024-02-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
