# Generated by Django 4.0.2 on 2024-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('employees', models.ManyToManyField(to='employees.Employee')),
            ],
        ),
    ]
