# Generated by Django 4.0.2 on 2024-02-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_user_id_alter_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.CharField(default='**********', max_length=10, verbose_name='EGN'),
        ),
    ]
